name: CI/CD MLflow Pipeline

# Trigger: Jalan setiap kali ada Push ke branch main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/fandadefchristian/Fraud-Detection-Experiment.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependencies Global (untuk menjalankan perintah mlflow)
    - name: Install MLflow & Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    # 4. Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Jalankan Training (MLflow Run)
    # Ini akan menjalankan 'MLProject' yang ada di folder MLProject
    # Hasil training (Metrics/Model) otomatis masuk ke DagsHub karena ENV VAR di atas
    - name: Run MLflow Project (Retraining)
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name "Fraud-Detection-Experiment"

    # 6. Build Docker Image dari Model Terakhir
    # Kita mengambil model terakhir yang tersimpan di run ini dan membungkusnya jadi Docker Image
    - name: Build Docker Image using MLflow
      run: |
        # Menggunakan script Python untuk mengambil Run ID terakhir secara otomatis & akurat
        # Kita menggunakan library mlflow yang sudah terinstall untuk mencari run terakhir dari eksperimen
        LAST_RUN_ID=$(python -c "import mlflow; client = mlflow.MlflowClient(); exp = client.get_experiment_by_name('Fraud_Detection_Experiment'); runs = client.search_runs(exp.experiment_id, max_results=1); print(runs[0].info.run_id)")
        
        # Cek apakah ID berhasil didapat
        if [ -z "$LAST_RUN_ID" ]; then
          echo "Error: Run ID tidak ditemukan!"
          exit 1
        fi

        echo "Building Docker for Run ID: $LAST_RUN_ID"
        
        # Build Docker Image menggunakan mlflow models build-docker
        # Nama image: username/nama-image:tag
        mlflow models build-docker \
          -m "runs:/$LAST_RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest" \
          --enable-mlserver

    # 7. Push Image ke Docker Hub
    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest