name: CI/CD MLflow Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/fandadefchristian/Fraud-Detection-Experiment.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install
    - name: Install MLflow & Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    # 4. Login Docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Run Training
    # PERBAIKAN: Nama eksperimen disamakan dengan Python script (Underscore)
    - name: Run MLflow Project (Retraining)
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name "Fraud_Detection_Experiment"

    # 6. Build Docker Image (METODE ROBUST: Download via Python -> Build Local)
    - name: Build Docker Image using MLflow
      run: |
        # Script Python untuk download artifact 'model' secara aman
        python -c "
        import mlflow
        import dagshub
        import sys
        
        # Init Auth
        dagshub.init(repo_owner='${{ secrets.DAGSHUB_USERNAME }}', repo_name='Fraud-Detection-Experiment', mlflow=True)
        
        client = mlflow.MlflowClient()
        # Cari Run ID dari eksperimen yang baru saja jalan
        exp = client.get_experiment_by_name('Fraud_Detection_Experiment')
        runs = client.search_runs(exp.experiment_id, max_results=1)
        
        last_run_id = runs[0].info.run_id
        print(f'Mendownload model dari Run ID: {last_run_id}')
        
        # Download folder 'model' ke folder lokal saat ini
        mlflow.artifacts.download_artifacts(run_id=last_run_id, artifact_path='model', dst_path='.')
        "

        echo "Building Docker Image from downloaded artifact..."
        
        # Build dari folder lokal 'model'
        mlflow models build-docker \
          -m "model" \
          -n "${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest" \
          --enable-mlserver

    # 7. Push
    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest